<?php

namespace Admin\AdminBundle\Repository;

/**
 * OurLoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OurLoggerRepository extends \Doctrine\ORM\EntityRepository
{
}
