<?php

namespace Admin\AdminBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategorieId($idCategorie, $page, $nbParPage)
    {
        $qb = $this->createQueryBuilder('p')
                ->join('p.categories', 'c')
                ->addSelect('c')
                ->setParameter('idC', $idCategorie)
                ->where('c.id = :idC')
        ;

        $query = $qb->getQuery();

        $query->setFirstResult(($page - 1) * $nbParPage)
            ->setMaxResults($nbParPage)
        ;

        return new Paginator($query, true);
    }

    public function getProduits($page, $nbParPage)
    {
        $query = $this->createQueryBuilder('p')
            ->getQuery()
        ;

        $query->setFirstResult(($page - 1) * $nbParPage)
            ->setMaxResults($nbParPage)
        ;

        return new Paginator($query, true);
    }
}
