<?php

namespace Admin\AdminBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategorieId($idCategorie)
    {
        $qb = $this->createQueryBuilder('p')
                ->join('p.categories', 'c')
                ->addSelect('c')
                ->setParameter('idC', $idCategorie)
                ->where('c.id = :idC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
